service:
  name: api-velog

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  stage: dev
  environment:
    SECRET_KEY: ${file(./env.json):SECRET_KEY}
    COCKROACHDB_HOST: ${file(./env.json):COCKROACHDB_HOST}
    COCKROACHDB_PW: ${file(./env.json):COCKROACHDB_PW}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DetachNetworkInterface"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - LAFTEL
            allowCredentials: false
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - LAFTEL
            allowCredentials: false
    vpc:
      securityGroupIds:
        - sg-5bc57830
      subnetIds:
        - subnet-d438debc