service:
  name: api-velog

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  stage: dev
  environment:
    SECRET_KEY: ${file(./env.json):SECRET_KEY}
    COCKROACHDB_HOST: ${file(./env.json):COCKROACHDB_HOST}
    COCKROACHDB_PW: ${file(./env.json):COCKROACHDB_PW}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DetachNetworkInterface"
        - "ec2:DeleteNetworkInterface"
        - "ses:SendEmail"
      Resource: "*"

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: 'https://velog.io'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors:
            origin: 'https://velog.io'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
    vpc:
      securityGroupIds:
        - sg-5bc57830
      subnetIds:
        - subnet-91481ef9
        - subnet-2c59dc60
        - subnet-4f59dc03

custom:
  apigwBinary:
    types:           #list of mime-types
      - 'multipart/form-data'
      - 'application/x-www-form-urlencoded'